### ISSUE TITLE
Add your name to README.md to test Gitflow

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/ML_pipeline_microbiome#18]
To test our Gitflow we will start by adding our names to the README.md. Everyone should clone the repo, pull, make a branch, add their name, and do a pull request for my review.

**Comment by kelly-sovacool** [comment]
Do you want us to do this on the same branch (e.g. I used `iss18`) and open one PR once everyone is done, or one branch & PR per person?

**Comment by BTopcuoglu** [comment]
A branch & a PR per person so we get some practice on using Gitflow. So you can go ahead and create a PR for yours @kelly-sovacool. 

And others, please don't forget to do a `git pull` before you do any contribution, please.

**Comment by kelly-sovacool** [comment]
Everything should work if you follow the [contributing instructions](https://github.com/SchlossLab/ML_pipeline_microbiome/blob/master/CONTRIBUTING.md), but feel free to ask for help if you run into problems!

**Comment by kelly-sovacool** [comment]
Looks like @zenalapp still needs to add her name to the list
