### ISSUE TITLE
Make permutation importance optional and not hard-coded

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/ML_pipeline_microbiome#3]
Permutation importance is optional at the moment but `perm=T` does not work.

**Comment by zmml** [comment]
When perm=T, the only data that can be used in Begum's

To make it an option for all users:
- [ ] Change permutation argument from `perm=T/F` to `perm=NULL/correlation_matrix.csv`
- [ ] Make example correlation matrix with code from `compute_correlation_matrix.R`
- [ ] Documentation on what the permutation test is and why you might want to use it
- [ ] Documentation on what the correlation matrix is, what it should look like, and how to generate it
- [ ] Add permutation argument flag for command line script
- [ ] Modify code in `permutation_importance.R` to read in correlation matrix 
- [ ] Modify code in `permutation_importance.R` to remove hard-coded list sizes 
- [ ] Test code to see if it works

**Comment by BTopcuoglu** [comment]
I created a `prepare_input_data.R` script to generate our test data `data/input_data.csv` and a correlation matrix needed for permutation importance `data/process/sig_flat_corr_matrix.csv`. Then the `main.R` will be called from the command line and `data/input_data.csv` will be given as an argument.

**Comment by kelly-sovacool** [comment]
When #19 is merged, there will be an optional flag `--permutation` for the user to control whether permutation importance is performed. Testing should include making sure that it works when called from both the command line and from within R.

**Comment by BTopcuoglu** [comment]
Only adding documentation steps needs to be done before closing this issue.
