### ISSUE TITLE
Find way to implement both load_caret_models scripts

### ISSUE THREAD

**Issue by lucas-bishop** [SchlossLab/ML_pipeline_microbiome#39]

**Comment by lucas-bishop** [comment]
only the load_caret_models_flux.R script is used in the pbs scripts, but for non-hpc users the load_caret_models.R script will be used....I think

**Comment by kelly-sovacool** [comment]
Fixing #74 may also fix this issue

**Comment by BTopcuoglu** [comment]
Closed with fixing #74 with PR #93
