### ISSUE TITLE
User-defined options as flags rather than positional arguments

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/ML_pipeline_microbiome#4]
Right now we call code/R/main.R with 4 positional arguments. Can we change that to flags?

**Comment by kelly-sovacool** [comment]
- Recommend `docopt` for parsing arguments.
    - http://docopt.org/
    - https://github.com/docopt/docopt.R

**Comment by kelly-sovacool** [comment]
@BTopcuoglu can you list the arguments you'd like to have, including both the old positional arguments and any new ones to add?

**Comment by BTopcuoglu** [comment]
@kelly-sovacool 
Right now I'm running with:
```
input <- commandArgs(trailingOnly=TRUE)
seed <- as.numeric(input[1]) # Seed for each datasplit
model <- input[2] # model name as a string provided as e.g. "L2_Logistic_Regression"
permutation <- as.numeric(input[3]) # 1 if permutation performed 
                                    # 0 if permutation not performed
outcome <- input[4] # outcome as a string provided as e.g. "dx"
```
We want to add:
(i) Input data (tsv)
(ii) Input hyperparameters as a dataframe (tsv)
