### ISSUE TITLE
Running Decision Tree causes error

### ISSUE THREAD

**Issue by wclose** [SchlossLab/ML_pipeline_microbiome#57]
`[1] "Not running permutation importance"
[1] "first outcome: normal"  "second outcome: cancer"
[1] "Machine learning formula:"
dx ~ .
<environment: 0x55698aa08028>
[1] "Decision_Tree"
Error in { : 
  task 1 failed - "need at least two non-NA values to interpolate"
Calls: run_model ... train.default -> nominalTrainWorkflow -> %op% -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
`

**Comment by BTopcuoglu** [comment]
Thanks @wclose for opening the issue.

I checked today and it runs successfully locally when I run it with the original dataset. I'm worried that the test data is the cause of the problem. Could you try running the Decision Tree and Random Forest on the cluster with the `data/test/input_data.tsv` and see if you are getting any errors?

If there are no issues with that, we can focus on the test data and why it is not working.

**Comment by BTopcuoglu** [comment]
I also noticed that the PR by Pat that removes NZV changes the data structure that could affect the permutation importance. I'll take a look at that at lab meeting.

**Comment by BTopcuoglu** [comment]
Tree-based methods give error with smaller datasets due to the large hyperparameters such as maxdepth=6.
