### ISSUE TITLE
Save data in results directory instead of data/temp

### ISSUE THREAD

**Issue by zenalapp** [SchlossLab/ML_pipeline_microbiome#63]
It's easier to find the results this way and follows best practices of naming things [[Noble 2009](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424)].

**Comment by BTopcuoglu** [comment]
I prefer to keep it this way as we shouldn't need to find any temp files once, combined files are made. What do you think @zenalapp ?
