### ISSUE TITLE
NZV

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/ML_pipeline_microbiome#71]
Maybe consider adding Pat's code in `model_pipeline.R`, to remove warnings when there are near 0 variance OTUs. 
```
	# Identify those columns that have no variance and then remove them. the following code assumes	
	# that the data frame has the outcome variable column first, as was set in the if-else code block	
	# above. This helps us avoid a nuisance warning that OTUs have zero variance.	
	non_zero_variance_cols <- logical()	
	non_zero_variance_cols[outcome] <- TRUE	
	non_zero_variance_cols <- c(non_zero_variance_cols, apply(data[,2:ncol(data)], 2, sd) != 0)	
	data <- data[,non_zero_variance_cols]

        preProcValues <- caret::preProcess(data, method = "range")	
       dataTransformed <- predict(preProcValues, data)
```

**Comment by NLesniak** [comment]
alternatively, you could add "nzv" to preProcess method
`preProcValues <- caret::preProcess(data, method = c("nzv", "range"))`
This will remove features with near zero variance and transform the data of the remaining columns

**Comment by BTopcuoglu** [comment]
@NLesniak and I discussed the best way to implement this. @NLesniak will do a PR to address this issue.
