### ISSUE TITLE
Fix data/caret_models structure and code/R/load_caret_models.R

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/ML_pipeline_microbiome#74]
Currently, there are R scripts in `data/caret_models`. Most of them are source code from the `caret` package, downloaded from GitHub. Two of them, `svmLinear3.R` and `svmLinear4.R`, are modified versions of the original code from `caret`. The script `code/R/load_caret_models.R` copies all of these files into the default R Library path. The purpose was to customize the svmLinear models. We need to preserve this purpose but fix some problems with the current implementation:

- All R code should go in the `R/` dir, per R Package requirements.
- `load_caret_models.R` should not modify the R Library, as that will have unintended consequences for users who use `caret` in other projects. The ultimate solution will likely delete this script.
- Any code from `caret`, modified or otherwise, should credit the original authors.

One potential solution is to fork the `caret` repo, modify those two files mentioned above, and include the forked version of `caret` as a dependency of this project ([related SO post](https://stackoverflow.com/questions/30493388/create-an-r-package-that-depends-on-another-r-package-located-on-github)). 

This issue must be fixed before this project can become an R package (#46).

**Comment by kelly-sovacool** [comment]
I forked caret to my [personal github](https://github.com/kelly-sovacool/caret) to initially test out this idea.

**Comment by JMAStough** [comment]
@kelly-sovacool have you made any progress with this? I'm thinking about spending some time trying to address it.

**Comment by kelly-sovacool** [comment]
@JMAStough I made a little progress [here](https://github.com/kelly-sovacool/caret) (just now added you as a collaborator). I incorporated Begüm's models in the package but can't get it to pass `devtools::check()`. Feel free to take a stab at it! Unfortunately this is low priority for me right now.

**Comment by BTopcuoglu** [comment]
@kelly-sovacool thanks for working on this. I found an option to solve this: https://topepo.github.io/caret/using-your-own-model-in-train.html

I'll work on this and will update the group.
