### ISSUE TITLE
Hardcoded correlation matrix

### ISSUE THREAD

**Issue by JMAStough** [SchlossLab/ML_pipeline_microbiome#78]
The correlation matrix used during permutation tests is built from OTU data, so when I tried to use my own assembly data to run a permutation, it didn't recognize any of the columns in the in the correlation matrix.

It would be nice to have the pipeline automatically generate a correlation matrix when using `--permutation`, but we could also specify how to do this in the documentation

**Comment by BTopcuoglu** [comment]
We hope that the user will generate their own correlation matrix based on their correlation criteria. However, we have an example R script and correlation matrix for the users to view before they make their own. We want to refer the user to https://github.com/SchlossLab/ML_pipeline_microbiome/blob/master/test/code/prepare_input_data.R. @JMAStough if you want to add more documentation to make that clear please don't hesitate to edit the README.md accordingly.

**Comment by JMAStough** [comment]
I can work on the documentation, but I can alos try to edit `prepare_input_data.R` to be called by the user if you'd like.
