### ISSUE TITLE
Change the script name to match the function name

### ISSUE THREAD

**Issue by BTopcuoglu** [SchlossLab/ML_pipeline_microbiome#8]
Let me know if the function name doesn't make sense, or if you think we should change the function name.

- [x] Make sure the names are changed in all the other scripts

**Comment by kelly-sovacool** [comment]
Closed above for demo, re-opening since we didn't fully resolve it.

**Comment by BTopcuoglu** [comment]
@tomkoset and @lucas-bishop I thought this might be a good start for the 3 of us to start changing other function names and scripts as Kelly did in the demo.

**Comment by lucas-bishop** [comment]
for a first simple change I changed the 'wilcoxon_test' function to use a verb; 'calculate_wilcoxon' but when I grep within the directory to change wherever else it is used I don't see anywhere. Is this function only used for testing?

**Comment by BTopcuoglu** [comment]
I think we caught all of them.
