### ISSUE TITLE
update README to include --level in example scripts

### ISSUE THREAD

**Issue by NLesniak** [SchlossLab/ML_pipeline_microbiome#83]
`Rscript code/R/main.R ...` examples do not work, due to missing --level argument
And error for missing argument is unclear and not helpful to know need all arguments
`Error: `
` usage: main.R --seed=<num> --model=<name> --data=<csv> --hyperparams=<csv> `
`--outcome=<colname> --level=<level> [--permutation]`
` usage: main.R --configfile=<yml>`
` usage: main.R --help`
`Execution halted`

**Comment by kelly-sovacool** [comment]
@BTopcuoglu how do you want the level option to work? I can add the option to the argument parser.

**Comment by BTopcuoglu** [comment]
:) yeah i just need to add it to README.md and testing. Thanks for keeping an eye out for the issues though 🥇

**Comment by NLesniak** [comment]
also lines 149, 151, 156 need level
line 158 - i think the .sh has moved from code/slurm/L2_Logistic_Regression.sh > run.sh?
line 163 - cat_csv_files.sh > bash/cat_csv_files.sh
